M48
; DRILL file {KiCad 9.0.6} date 2026-03-31T20:38:50+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-31T20:38:50+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X128.27Y-74.93
X128.27Y-146.05
X203.2Y-74.93
X203.2Y-146.05
M30
