M48
; DRILL file {KiCad 9.0.6} date 2026-03-31T21:03:47+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-31T21:03:47+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X123.19Y-68.58
X123.19Y-115.57
X187.96Y-68.58
X187.96Y-115.57
M30
